-- MySQL Script generated by MySQL Workbench
-- dom 24 nov 2019 14:53:49 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portal_traumato_barto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portal_traumato_barto` ;

-- -----------------------------------------------------
-- Schema portal_traumato_barto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal_traumato_barto` DEFAULT CHARACTER SET utf8 ;
USE `portal_traumato_barto` ;

-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`grupo_pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`grupo_pregunta` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`grupo_pregunta` (
  `id_grupo_pregunta` INT NOT NULL AUTO_INCREMENT,
  `descripcion_grupo_pregunta` VARCHAR(140) NOT NULL,
  `puntuacion_maxima_score` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_pregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`tipo_respuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`tipo_respuesta` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`tipo_respuesta` (
  `id_tipo_respuesta` INT NOT NULL AUTO_INCREMENT,
  `descripcion_tipo_respuesta` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id_tipo_respuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`pregunta` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`pregunta` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `descripcion_pregunta` VARCHAR(140) NOT NULL,
  `id_grupo_pregunta` INT NOT NULL,
  `id_tipo_respuesta` INT NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  INDEX `id_grupo_pregunta_idx` (`id_grupo_pregunta` ASC),
  INDEX `id_tipo_respuesta_idx` (`id_tipo_respuesta` ASC),
  CONSTRAINT `id_grupo_pregunta`
    FOREIGN KEY (`id_grupo_pregunta`)
    REFERENCES `portal_traumato_barto`.`grupo_pregunta` (`id_grupo_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_respuesta`
    FOREIGN KEY (`id_tipo_respuesta`)
    REFERENCES `portal_traumato_barto`.`tipo_respuesta` (`id_tipo_respuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`respuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`respuesta` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`respuesta` (
  `id_respuesta` INT NOT NULL AUTO_INCREMENT,
  `descripcion_respuesta` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id_respuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`tipo_encuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`tipo_encuesta` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`tipo_encuesta` (
  `id_tipo_encuesta` INT NOT NULL,
  `descripcion_tipo_encuesta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_encuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`tipo_cirugia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`tipo_cirugia` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`tipo_cirugia` (
  `id_tipo_cirugia` INT NOT NULL AUTO_INCREMENT,
  `descripcion_tipo_cirugia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_cirugia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`persona` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `fecha_naciemiento` DATE NOT NULL,
  `sexo` ENUM('masculino', 'femenino', 'otro') NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`paciente` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `imc` FLOAT NOT NULL,
  `id_obra_social` INT NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_paciente`),
  INDEX `id_persona_idx` (`id_persona` ASC),
  CONSTRAINT `id_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `portal_traumato_barto`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`cirugia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`cirugia` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`cirugia` (
  `id_cirugia` INT NOT NULL AUTO_INCREMENT,
  `descripcion_cirugia` INT NOT NULL,
  `id_tipo_cirugia` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_cirugia`),
  INDEX `id_tipo_cirugia_idx` (`id_tipo_cirugia` ASC),
  INDEX `id_paciente_idx` (`id_paciente` ASC),
  CONSTRAINT `id_tipo_cirugia`
    FOREIGN KEY (`id_tipo_cirugia`)
    REFERENCES `portal_traumato_barto`.`tipo_cirugia` (`id_tipo_cirugia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `portal_traumato_barto`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`encuesta_cabecera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`encuesta_cabecera` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`encuesta_cabecera` (
  `id_encuesta_cabecera` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_encuesta` INT NOT NULL,
  `id_cirugia` INT NOT NULL,
  `descripcion_encuesta_cabecera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_encuesta_cabecera`),
  INDEX `id_tipo_encuesta_idx` (`id_tipo_encuesta` ASC),
  INDEX `id_cirugia_idx` (`id_cirugia` ASC),
  CONSTRAINT `id_tipo_encuesta`
    FOREIGN KEY (`id_tipo_encuesta`)
    REFERENCES `portal_traumato_barto`.`tipo_encuesta` (`id_tipo_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cirugia`
    FOREIGN KEY (`id_cirugia`)
    REFERENCES `portal_traumato_barto`.`cirugia` (`id_cirugia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`encuesta_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`encuesta_detalle` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`encuesta_detalle` (
  `id_encuesta_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_encuesta_cabecera` INT NOT NULL,
  `id_pregunta` INT NOT NULL,
  `id_respuesta` INT NOT NULL,
  PRIMARY KEY (`id_encuesta_detalle`),
  INDEX `id_pregunta_idx` (`id_pregunta` ASC),
  INDEX `id_respuesta_idx` (`id_respuesta` ASC),
  INDEX `id_encuesta_cabecera_idx` (`id_encuesta_cabecera` ASC),
  CONSTRAINT `id_pregunta`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `portal_traumato_barto`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_respuesta`
    FOREIGN KEY (`id_respuesta`)
    REFERENCES `portal_traumato_barto`.`respuesta` (`id_respuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_encuesta_cabecera`
    FOREIGN KEY (`id_encuesta_cabecera`)
    REFERENCES `portal_traumato_barto`.`encuesta_cabecera` (`id_encuesta_cabecera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`permisos` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`permisos` (
  `id_permisos` INT NOT NULL AUTO_INCREMENT,
  `crear_encuesta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_paciente` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_usuario` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_cirugia` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_pregunta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_respuesta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_tipo_respuesta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_grupo_pregunta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_tipo_encuesta` TINYINT(1) NOT NULL DEFAULT 0,
  `crear_tipo_cirugia` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_permisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`usuario` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `email_alternativo` VARCHAR(45) NULL,
  `eliminado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `portal_traumato_barto`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`rol` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `id_permisos` INT NOT NULL,
  `descripcion_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  INDEX `id_permisos_idx` (`id_permisos` ASC),
  CONSTRAINT `id_permisos`
    FOREIGN KEY (`id_permisos`)
    REFERENCES `portal_traumato_barto`.`permisos` (`id_permisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario_rol`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  INDEX `id_rol_idx` (`id_rol` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `portal_traumato_barto`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `portal_traumato_barto`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_traumato_barto`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal_traumato_barto`.`token` ;

CREATE TABLE IF NOT EXISTS `portal_traumato_barto`.`token` (
  `id_token` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_expiracion` DATETIME NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_token`),
  INDEX `fk_token_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_token_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `portal_traumato_barto`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
